language: node_js
node_js:
- '8'
sudo: required
cache: yarn
notifications:
  email: false
git:
  depth: 1
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
- sudo apt-get install -y python3-pip
- pip3 install --user awscli
script:
- mkdir out
- yarn build
- bash ./scripts/prepare-deploy.sh
- aws s3 rm s3://patternfly-org-staging --recursive # Remove current files
- aws s3 sync out s3://patternfly-org-staging # Upload new files
- aws cloudfront create-invalidation --distribution-id EQE4NPRH0CQXJ --paths "/*" # Invalidate everything on CDN
