language: node_js
node_js:
  - "8"
sudo: required
cache: yarn
deploy:
  provider: surge
  skip_cleanup: true
  project: ./out/
  domain: patternfly.surge.sh
  on: monorepo
notifications:
  email: false
git:
  depth: 1
before_install:
- npm install -g lerna grunt-cli gatsby-cli
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
- yarn bootstrap
install: true
script:
- yarn build
after_success: |
  mkdir -p out/4.0
  cp -R packages/patternfly-3/_site/. out/
  # cp -R packages/patternfly-4/public/. out/4.0/
